config/routes.rb
Rails.application.routes.draw do
  get 'mainpage', to: 'main#mainpage'
  get 'contentdetail' , to: 'main#contentdetail'
  get '_header' , to: 'main#header'
  get 'pagedetail' , to: 'main#pagedetail'
  get 'createpage' , to: 'main#createpage'
  get 'signup' , to: 'main#signup'
  get 'signin' , to: 'main#signin'
  get 'userprof', to: 'main#userprof'
  get 'searchresult', to: 'main#searchresult'
  get 'fav', to: 'main#fav'
  get 'fav2', to: 'main#fav2'
  resources :boards

  root to: "main#mainpage"

end

app/models/board.rb
class Board < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { in: 4..127 }
  validates :editor, presence: true, length: { in: 1..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params_board)
    @board.save
    redirect_to board_url(@board)
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update_attributes(params_board)
    redirect_to board_url(@board)
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_url
  end

  private

  def params_board
    params.require(:board).permit(:title, :editor, :image)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  def mainpage
  end
  def _header
  end
  def pagedetail
  end
  def createpage
  end
  def signup
  end
  def signin
  end
  def userprof
  end
  def searchresult
  end
  def fav
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/boards/_footer2.html.haml
/ここはフッターです

#final
  #copyrightpos
    #contact
      %span#contactline
        %strong Contact
      %br
        %span{:style => "font-size:20px;"}
          Tsukishima Chuo-ku
          %br
            Tokyo, Japan
    %hr#footerhr
      %p#copyright
        Copyright © 2015 RYOH HASEGAWA All rights reserved.

app/views/boards/_header2.html.haml
/ここはヘッダーです

%nav#header
  %ul.content
    .float-left
      = link_to mainpage_path do
        %img.servicetitle.inline-block.middle{:src => "assets/mainlogo.jpg"}
      .clear
    .float-right
      %li
        %a{:href =>""}
          %i.fa.fa-caret-down.inline-block.middle
      %li
        = link_to signin_path do
          ログイン
      %li
        = link_to signup_path do
          アカウント作成
      %li{:style => "color:white;background-color:rgb(125,19,81)"}
        = link_to boards_path, style: "color: white;" do
          ストーリーを書く
      .clear

/ここまでがヘッダーです

app/views/boards/edit.html.haml
= link_to @board.title, board_path(@board)
%hr
  %h1 Boards#edit
  = form_for @board do |f|
    タイトル: #{f.text_field :title}
    %br
      作成者名: #{f.text_field :editor}
      %br
        = submit_tag

app/views/boards/index.html.haml
= render partial: "header2"
%div#deep
  %div#newslead
    = link_to "新しい物語をつくる", new_board_path
  - @boards.each do |board|
    = link_to board.title, board_path(board)
= render partial: "footer2"

app/views/boards/new.html.haml
%dv#bod
  = link_to "「物語」一覧に戻る", boards_path
  %hr
  = form_for :board, url: boards_path, method: :post do |f|
    タイトル　　　:
    = f.text_field :title
    %br
    ストーリー内容:
    = f.text_field :editor
    %br
    = f.file_field :image
    = f.submit '保存'
= render partial: "footer2"

app/views/boards/show.html.haml
= link_to "スレッド一覧に戻る", boards_path
%hr
  %h1= @board.title
  = link_to "タイトルを編集する", edit_board_path(@board)
  = link_to "削除する", board_path(@board), method: :delete, data: { confirm: "本当に削除しますか？" }
  %hr/

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title HamlApp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{class: "#{controller.controller_path + " " + controller.action_name}"}
    = yield

app/views/main/_footer.html.haml
/ここはフッターです

#final
  #copyrightpos
    #contact
      %span#contactline
        %strong Contact
      %br
        %span{:style => "font-size:20px;"}
          Tsukishima Chuo-ku
          %br
            Tokyo, Japan
    %hr#footerhr
      %p#copyright
        Copyright © 2015 RYOH HASEGAWA All rights reserved.

app/views/main/_header.html.haml
/ここはヘッダーです

%nav#header
  %ul.content
    .float-left
      = link_to mainpage_path do
        %img.servicetitle.inline-block.middle{:src => "assets/mainlogo.jpg"}
      .clear
    .float-right
      %li
        %a{:href =>""}
          %i.fa.fa-caret-down.inline-block.middle
      %li
        = link_to signin_path do
          ログイン
      %li
        = link_to signup_path do
          アカウント作成
      %li{:style => "color:white;background-color:rgb(125,19,81)"}
        = link_to createpage_path, style: "color: white;" do
          ストーリーを書く
      .clear

/ここまでがヘッダーです

app/views/main/createpage.html.haml
= render partial: "header"

%div
  %div{:style => "padding-top:85px"}
    #letsshare.col-md-6
      あなただけの
      %br
        物語をシェアしましょう
    .col-md-6{:style => "padding-top:50px"}
      %p
        %button.btn.btn-primary.btn-lg{:type => "button"} 下書き保存
.clear
.writesection
  %p{:style => "font-size:20px; color:rgb(156,156,156)"}
    %br
      タグを追加
.btnposi
  %span.input-group-btn
    %button.btn.btn-warning{:type => "button"} 保存
.writesection
  %p{:style => "font-size:20px; color:rgb(156,156,156)"}
    %br
      タイトルを追加
.btnposi
  %span.input-group-btn
    %button.btn.btn-warning{:type => "button"} 保存
.writesection2
  %p{:style => "font-size:20px; color:rgb(156,156,156)"}
    %br
      %br
        %br
          物語のダイジェストを
          %br
            リード文にまとめてみましょう
.btnposi
  %span.input-group-btn
    %button.btn.btn-warning{:type => "button"} 保存
.putanime
  .col-md-3.putanimebox
    .tsuika
      ＋
    .tsuikaexpla
      テクストを
      %br
        追加する
  .col-md-3.putanimebox
    .tsuika
      ＋
    .tsuikaexpla
      写真を
      %br
        追加する
  .col-md-3.putanimebox
    .tsuika
      ＋
    .tsuikaexpla
      動画を
      %br
        追加する
  .col-md-3.putanimebox
    .tsuika
      ＋
    .tsuikaexpla
      ブロックを
      %br
        追加する
.clear
.writingexample

= render partial: "footer"

app/views/main/fav.html.haml
= render partial: "header"

%div{:style => "padding-top: 80px;"}
.userboxp
  %img.withinprofbox{:src => "assets/ryoh.jpg"}
    .withinprofbox2
      リョー
.allfav
  お気に入り一覧
.clear
.resultcontent
  .inline-block
    %img{:src => "assets/hisi.jpg", :style => "height: 280px; width: 348px;"}
  .hisistorybk.inline-block
    .hisistory
      女傑・ヒシアマゾン
      %br
        闘いに明け暮れた日々
    .hisicontent
      闘いに明け暮れた日々は終わった。
      %br
        有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
        %br
          圧勝を演じたサクラローレルに注がれていた。
          %br
            ヒーローの影に隠れた誇り高き敗者...
            %br
              （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/karston.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        アイビスSDといえば、
        %br
          カルストンライトオ
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/brubon.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        ミホノブルボンには惜敗
        %br
          それでも見せた意地
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/tapcity.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        大器晩成のお手本
        %br
          タップダンスシチーの生涯
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  %nav{:style => "text-align:center; padding-top:30px"}
    %ul.pagination{:width => "100%"}
      %li
        %a{"aria-label" => "Previous", :href => "#"}
          %span{"aria-hidden" => "true"} &laquo;
      %li
        %a{:href => "#"} 1
      %li
        %a{:href => "#"} 2
      %li
        %a{:href => "#"} 3
      %li
        %a{:href => "#"} 4
      %li
        %a{:href => "#"} 5
      %li
        %a{"aria-label" => "Next", :href => "#"}
          %span{"aria-hidden" => "true"} &raquo;

= render partial: "footer"

app/views/main/mainpage.html.haml
/メインページです
= render partial: "header"

#main
  .top.table
    #concept
      %p#conceptdetail
        時代を彩った名馬たち
        %br
        戦績は残せなかったものの、
        %br
        思い入れ深い愛馬。
        %br
        競走馬の数だけ、
        %br
        そこには物語がある。
        %br
        戦績だけでは語りきれない
        %br
        あなただけの
        %br
        物語をシェアしましょう
  #main2
    %h1{:style => "text-align:center;font-family:HiraMinProN-W6;font-size:35px;"} すべての馬には物語がある
    .search-content
      .input-group
        %input.form-control{:placeholder => "馬名・ユーザー名・キーワード", :type => "text"}
        %span.input-group-btn
          %button.btn.btn-success{:type => "button"} 物語を探す
    .posts
      .row
        .col-md-6
          .img-back.suzuka
            .white-back
              .post-content
              %a{:href => "index2.html"}
                = link_to "影さえも踏ませなかったサイレンススズカ", pagedetail_path
                %a{:href => "index2.html"}
                .text
                  %p あああああああああああああああああああああああああああああああああああああああああああああああああ
                %img#prof1{:src => "assets/prof1.jpg"}
                %span#namehr Ryoh Hasegawa
                %img#book1{:src => "assets/book1.jpg"}
                %span{:style => "font-size:40px;font-weight:bold;position:absolute;top:230px;left:235px"} 18
                %a{:href => "index8.html"}
                  %img#star1{:src => "assets/star1.jpg"}/
                %span{:style => "font-size:40px;font-weight:bold;position:absolute;top:230px;left:350px"} 22
        .col-md-6
          .img-back.oguri
            .white-back
        .row
          .col-md-4
            .img-back.orfe
              .white-back
          .col-md-4
            .img-back.kinkame
              .white-back
          .col-md-4
            .img-back.staygold
              .white-back
      .row
        .col-lg-6
          .img-back.sinkuri
            .white-back
              .post-back
                %3.title 影さえも踏ませなかったサイレンススズカ
                .text
                  %p あああああああああああああああああああああああああああああああああああああああああああああああああ
                %img#prof1{:src => "assets/prof1.jpg"}
                %span#namehr Ryoh Hasegawa
                %img#book1{:src => "assets/book1.jpg"}
                %span{:style => "font-size:40px;font-weight:bold;position:absolute;top:230px;left:235px"} 18
                %img#star1{:src => "assets/star1.jpg"}
                %span{:style => "font-size:40px;font-weight:bold;position:absolute;top:230px;left:350px"} 22
        .col-lg-6
          .img-back.yukichan
            .white-back
      .row
        .col-md-4
          .img-back.mayano
            .white-back
        .col-md-4
          .img-back.durandal
            .white-back
        .col-md-4
          .img-back.dscarlett
            .white-back
    .pagenation-content
      %nav
        %ul.pagination{:width => "100%"}
          %li
            %a{"aria-label" => "Previous", :href => "#"}
              %span{"aria-hidden" => "true"} &laquo;
          %li
            %a{:href => "#"} 1
          %li
            %a{:href => "#"} 2
          %li
            %a{:href => "#"} 3
          %li
            %a{:href => "#"} 4
          %li
            %a{:href => "#"} 5
          %li
            %a{"aria-label" => "Next", :href => "#"}
              %span{"aria-hidden" => "true"} &raquo;

= render partial: "footer"

app/views/main/pagedetail.html.haml
= render partial: "header"

.post-header
  .header-left.float-left
    .tag-content.float-left
      %a.tag{:href => ""}
        %img.tag-img.inline-block.middle{:src => "assets/tagicon.png", :width => "40"}
          .inline-block.middle
            武豊
      %a.tag{:href => ""}
        %img.tag-img.inline-block.middle{:src => "assets/tagicon.png", :width => "40"}
          .inline-block.middle
            金鯱賞
      %a.tag{:href => ""}
        %img.tag-img.inline-block.middle{:src => "assets/tagicon.png", :width => "40"}
          .inline-block.middle
            予後不良
      %a.tag{:href => ""}
        %img.tag-img.inline-block.middle{:src => "assets/tagicon.png", :width => "40"}
          .inline-block.middle
            大逃げ
      .date
        公開日：3月15日
    .fav-title
      .fav-content.float-left
        .favcon-upper.table
          .table-cell
            %i.fa.fa-star.inline-block.middle
            .fav-number.inline-block.middle
              37
            .text
              お気に入り
          .table-cell
            .fav-number
              35537
            .text
              view
        .favcon-bottom
          %a.btn.inline-block{:href => ""}
            %i.fa.fa-star.inline-block.middle
            .inline-block.middle
              お気に入りに追加
      .title-content.float-left
        %strong
          影さえ踏ませず、
          %br
            散ったサイレンススズカ
      .clear
  .header-right.float-left
    .media
      .media-left.media-middle
        %a{:href => "index6.html"}
        = link_to userprof_path do
          %img#ryoh2.ryohimg{:src => "assets/morikazu.png", :width => "80"}/
      .media-body.media-middle
        %h1#ryoh3
          %a{:href => "index6.html"} 田中一郎
        %img.inline-block.middle{:src => "assets/book1.jpg", :width => "30"}
          .num.inline-block.middle
            9
  .clear
.socialshare
  / Twitter
  %a.btn.btn-twitter{:href => "http://twitter.com/home?status=", :target => "_blank", :title => "Share on Twitter"}
    %i.fa.fa-twitter
    Twitter
  / Facebook
  %a.btn.btn-facebook{:href => "https://www.facebook.com/sharer/sharer.php?u=", :target => "_blank", :title => "Share on Facebook"}
    %i.fa.fa-facebook
    Facebook
  / Google+
  %a.btn.btn-googleplus{:href => "https://plus.google.com/share?url=", :target => "_blank", :title => "Share on Google+"}
    %i.fa.fa-google-plus
    Google+
  / LinkedIn
  %a.btn.btn-linkedin{:href => "http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=", :target => "_blank", :title => "Share on LinkedIn"}
    %i.fa.fa-linkedin
    LinkedIn
.maintext
  まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打っては、他馬を置き去りにするそのレーススタイルに心を奪われた。6連勝で臨んだ天皇賞（秋）においての故障は、東京競馬場で目の当たりにし、心を痛めた。特に思い出深いレースをいくつか辿りながら、彼への思いを回顧したい。
.row.memorycontent
  .col-lg-6
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/tEWYysSkkCk", :width => "420"}
  .col-lg-6
    .dougacomment
      .titlesuzuka
        俺的スズカ史上最高レース
      .titlesuzuka2
        まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打っては、他馬を置き去りにするそのレーススタイルに心を奪われた。6連勝で臨んだ天皇賞（秋）においての故障は、東京競馬場で目の当たりにし、心を痛めた。
.row.memorycontent
  .col-lg-6
    .dougacomment2
      .titlesuzuka3
        ユタカも実は...
      .titlesuzuka2
        まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打っては、他馬を置き去りにするそのレーススタイルに心を奪われた。6連勝で臨んだ天皇賞（秋）においての故障は、東京競馬場で目の当たりにし、心を痛めた。
  .col-lg-6
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/h7KAmSR4_fI", :width => "420"}
.row.memorycontent
  .col-lg-6
    %img{:height => "315", :src => "assets/ceme.jpg", :width => "420"}
  .col-lg-6
    .dougacomment3
      .titlesuzuka5
        俺的スズカ史上最高レース
      .titlesuzuka4
        まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打っては、他馬を置き去りにするそのレーススタイルに心を奪われた。6連勝で臨んだ天皇賞（秋）においての故障は、東京競馬場で目の当たりにし、心を痛めた。
.sss
  / Twitter
  %a.btn.btn-twitter{:href => "http://twitter.com/home?status=", :target => "_blank", :title => "Share on Twitter"}
    %i.fa.fa-twitter
    Twitter
  / Facebook
  %a.btn.btn-facebook{:href => "https://www.facebook.com/sharer/sharer.php?u=", :target => "_blank", :title => "Share on Facebook"}
    %i.fa.fa-facebook
    Facebook
  / Google+
  %a.btn.btn-googleplus{:href => "https://plus.google.com/share?url=", :target => "_blank", :title => "Share on Google+"}
    %i.fa.fa-google-plus
    Google+
  / LinkedIn
  %a.btn.btn-linkedin{:href => "http://www.linkedin.com/shareArticle?mini=true&url=&title=&summary=", :target => "_blank", :title => "Share on LinkedIn"}
    %i.fa.fa-linkedin
    LinkedIn
.comments
  %hr#hrline
    %i.fa.fa-comments{:width => "100px"}
    .inline-block.middle{:style => "color:rgb(56,171,148); margin-bottom:10px; margin-left:5px; font-size:20px"}
      コメント
    .inline-block.middle{:style => "margin-bottom:10px"}
      2件
.commentrow
  .col-md-4
    %img#yahman.float-right{:src => "assets/yahman.jpg"}
  .col-md-8
    .commentuser
      yahman
    .commentext
      まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打って
.comments
  %hr#commentline
.commentrow
  .col-md-4
    %img#yahman.float-right{:src => "assets/ukun.jpg"}
  .col-md-8
    .commentuser
      うっくん
    .commentext
      まだ大学生だった頃、ハマったばかりの競馬で、すぐに虜となった愛馬がサイレンススズカだった。どんなレース、どんな展開でも大逃げを打って
.comments
  %hr#commentline
.commentrow
  .col-md-4
    %img#yahman.float-right{:src => "assets/tokida.jpg"}
  .col-md-8
    .usercomment
      %div{:style => "color:rgb(121, 116, 116);"}
        コメントを入力
<div class="clear" width"0">
.commentrow1
  .col-md-4.usertokida
    時田 泰
  .col-md-8
    .commentext
      %span.input-group-btn
        %button.btn.btn-success{:type => "button"} 物語を探す
.otherstory
  %a{:href => ""}
    %img.tag-img.inline-block.middle{:src => "assets/tagicon.png", :width => "40"}
      .inline-block.middle
        武豊
      .inline-block.middle.otherstory2
        を含む他のストーリーを読む
.otherstory3
  .col-md-4
    .img-back.mayano
      .white-back
  .col-md-4
    .img-back.durandal
      .white-back
  .col-md-4
    .img-back.dscarlett
      .white-back
.clear
.findother
  .float-right.motto
    （もっと探す）

= render partial: "footer"

app/views/main/searchresult.html.haml
= render partial: "header"

.col-md-4
  .searchresult
    検索結果
.col-md-4.relatedtag
  関連タグ
.col-md-4.relatedtag2.inline-block
  .inline-block
    %i.fa.fa-tag{:style => "font-size:30px"}
    .tagrace.inline-block
      有馬記念
  .inline-block
    %i.fa.fa-tag{:style => "font-size:30px"}
    .tagrace.inline-block
      有馬記念
.clear
.resultcontent
  .inline-block
    %img{:src => "assets/hisi.jpg", :style => "height: 280px; width: 348px;"}
  .hisistorybk.inline-block
    .hisistory
      女傑・ヒシアマゾン
      %br
        闘いに明け暮れた日々
    .hisicontent
      闘いに明け暮れた日々は終わった。
      %br
        有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
        %br
          圧勝を演じたサクラローレルに注がれていた。
          %br
            ヒーローの影に隠れた誇り高き敗者...
            %br
              （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/karston.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        アイビスSDといえば、
        %br
          カルストンライトオ
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/brubon.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        ミホノブルボンには惜敗
        %br
          それでも見せた意地
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  .hisiblock
    .inline-block
      %img{:src => "assets/tapcity.jpg", :style => "height: 280px; width: 348px;"}
    .hisistorybk.inline-block
      .hisistory
        大器晩成のお手本
        %br
          タップダンスシチーの生涯
      .hisicontent
        闘いに明け暮れた日々は終わった。
        %br
          有馬記念の熱狂のあとには、一瞬の静寂が訪れる。大観衆の眼差しは、
          %br
            圧勝を演じたサクラローレルに注がれていた。
            %br
              ヒーローの影に隠れた誇り高き敗者...
              %br
                （続きを読む）
  %nav{:style => "text-align:center; padding-top:30px"}
    %ul.pagination{:width => "100%"}
      %li
        %a{"aria-label" => "Previous", :href => "#"}
          %span{"aria-hidden" => "true"} &laquo;
      %li
        %a{:href => "#"} 1
      %li
        %a{:href => "#"} 2
      %li
        %a{:href => "#"} 3
      %li
        %a{:href => "#"} 4
      %li
        %a{:href => "#"} 5
      %li
        %a{"aria-label" => "Next", :href => "#"}
          %span{"aria-hidden" => "true"} &raquo;

= render partial: "footer"

app/views/main/signin.html.haml
.purplehead
.signuppage1
  .signuppage2
    .toprogo.inline-block.middle
      %img.inline-block.sublogo{:src => "assets/sublogo.jpg"}
    .useradd2
      .fabspace
      .fblog5
        .fblog8
          Facebookアカウントでログイン
      .orline
        %hr.orlines1.inline-block
          .inline-block.oror{:style => "color:rgb(159,159,162);"}
            or
          %hr.orlines2.inline-block
      .mailboxes
        %img.mailgray.inline-block{:src => "assets/mailgray.png"}
          .mailgray2.inline-block
            メールアドレス
      .passboxes
        %img.passgray.inline-block{:src => "assets/passboxes.png"}
          .passgray2.inline-block
            パスワード
      .fabspace
      .fblog4
        .fblog2
          ログインする
    .alreadyuse
      %div
        初めての方は
        %a{:href => "index4.html"}> ユーザー登録
        してください
      %div
        パスワードを忘れた方は
        %a{:href => ""} こちら

= render partial: "footer"

app/views/main/signup.html.haml
.purplehead
.signuppage1
  .signuppage2
    .toprogo.inline-block.middle
      %img.inline-block.sublogo{:src => "assets/sublogo.jpg"}
    .useradd
      .useraddrow
        %img.usericon.inline-block{:src => "assets/usericon.png"}
          .useraddtext.inline-block
            ユーザー登録
      .fblog
        .fblog2
          Facebookアカウントで登録
      .fbcaution
        許可なくFacebookに投稿することはありません
      .orline
        %hr.orlines1.inline-block
          .inline-block.oror{:style => "color:rgb(159,159,162);"}
            or
          %hr.orlines2.inline-block
      .mailboxes
        %img.mailgray.inline-block{:src => "assets/mailgray.png"}
          .mailgray2.inline-block
            メールアドレス
      .passboxes
        %img.passgray.inline-block{:src => "assets/passboxes.png"}
          .passgray2.inline-block
            パスワード
      .passboxes
        %img.passgray.inline-block{:src => "assets/passboxes.png"}
          .passgray3.inline-block
            パスワード（確認）
      .fbcaution2
        下記の登録ボタンを押した場合、
        %br
          利用規約に同意したものとみなされます
      .fblog4
        .fblog2
          ユーザー登録する
    .alreadyuse
      %div
        すでにアカウントを持っている方は、
        %a{:href => "index5.html"}> コチラ
        からログインしてください

= render partial: "footer"